version: "3"
services:
  workspace:
    build:
      context: ./workspace
      args:
        - VARIANT=1.17-bullseye
        - NODE_VERSION=lts/*
    env_file:
      - ./workspace/docker.env
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 1m

  minecraft:
    image: itzg/minecraft-server
    volumes:
      - ./minecraft/data:/data
    env_file:
      - ./minecraft/docker.env
    ports:
      - 25565:25565
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 1m
